namespace:
  name: sandbox

replicaCount: 1

image:
  name: brianpzaide/techtrends
  tag: latest
  pullpolicy: ifNotPresent

resources:
  requests:
    CPU: 250m
    memory: 64Mi
  limits:
    CPU: 500m
    memory: 128Mi

containerPort: 3111

service:
  port: 4111
  targerPort: 3111
  protocol: TCP
  type: ClusterIP

livenessProbe:
  path: /healthz

readinessProbe:
  path: /healthz
