namespace:
  name: staging

replicaCount: 3

image:
  repository: brianpzaide/techtrends
  tag: latest
  pullpolicy: IfNotPresent

resources:
  requests:
    CPU: 300m
    memory: 90Mi
  limits:
    CPU: 500m
    memory: 128Mi

containerPort: 3111

service:
  port: 5111
  targerPort: 3111
  protocol: TCP
  type: ClusterIP

livenessProbe:
  path: /healthz

readinessProbe:
  path: /healthz
