namespace:
  name: sandbox

replicaCount: 1

image:
  repository: brianpzaide/techtrends
  tag: latest
  pullpolicy: IfNotPresent

resources:
  requests:
    CPU: 250m
    memory: 64Mi
  limits:
    CPU: 500m
    memory: 128Mi

containerPort: 3111

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

livenessProbe:
  path: /healthz
  port: 3111

readinessProbe:
  path: /healthz
  port: 3111
